### ISSUE TITLE
Lack of documentation

### ISSUE THREAD

**Issue by thibaultmeyer** [mariussoutier/sbt-concat#2]
Hi,

is it possible to have a more documentation about how to compile your plugin (sbt web-pipeline doesn't work) and how to integrate it on an existing Play 2.3+ project ?

Thanks you

```
C:\Users\thiba\Desktop\sbt-concat-master>sbt
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
[info] Loading project definition from C:\Users\thiba\Desktop\sbt-concat-master\project
[info] Set current project to sbt-concat (in build file:/C:/Users/thiba/Desktop/sbt-concat-master/)
> web-pipeline
[error] Not a valid command: web-pipeline
[error] Not a valid project ID: web-pipeline
[error] Expected ':' (if selecting a configuration)
[error] Not a valid key: web-pipeline
[error] web-pipeline
[error]             ^
>
```

**Comment by mariussoutier** [comment]
Quoting from the README

> This is an **example** of a simple sbt-web plugin.
> 
> Also check out the [slides](http://www.slideshare.net/marius-soutier/sbt-webintro) for a talk I gave about sbt-web.

**Comment by mariussoutier** [comment]
You can also check out these blog posts:
- http://mariussoutier.com/blog/2014/10/20/intro-sbt-web/
- http://mariussoutier.com/blog/2014/12/07/understanding-sbt-sbt-web-settings/

**Comment by thibaultmeyer** [comment]
Hi,

I understand that is a simple plugin for sbt-web, but how to use it in the Play application (by example) ? I have in mind to use this plugin skeleton to develop a new version of Uglify. In fact, nether your plugin or sbt-uglify compile or give information how to set up an "devel" environment.

Do you have more information how to use this project ?

**Comment by mariussoutier** [comment]
That's because it's always the same with all sbt plugins, so you should check out the sbt documentation about sbt plugins, and then read my blog posts or the sbt-web documentation.
